env: [ CARGO_TERM_COLOR=always ]
cache:
  directories: [ $HOME/docker-cache ]
jobs:
  include:

    - stage: Reproducible builds
      name: Reproducible builds
      script:
      - >
        git submodule update --init --recursive &&
        docker build -t bwt-builder - < libbwt/bwt/scripts/builder.Dockerfile &&
        gzip -d < ~/docker-cache/images.tar.gz | docker load &&
        echo -e tr''avis_fo''ld:start:build\\nBuilding... &&

        mkdir -p libbwt/dist && echo x > libbwt/dist/foobar.tar.gz &&

        echo Packaging libbwt-nodejs... &&
        docker run -u `id -u` -v `pwd`:/usr/src/libbwt-nodejs -w /usr/src/libbwt-nodejs \
                   -e LIBBWT_DIST=/usr/src/libbwt-nodejs/libbwt/dist \
                   -e HOME=/tmp \
                   --entrypoint scripts/build.sh node:14 &&
        echo tr''avis_fol''d:end:build
      - >
        echo '------' && sha256sum *.* &&
        echo '------ package.json ----' && cat package.json &&
        echo '------ npm-shrinkwrap.json ----' && cat npm-shrinkwrap.json &&
        apt-install -u curl && curl --upload-file dist/libbwt-nodejs-0.0.0.tgz https://transfer.sh/libbwt-nodejs.tar.gz &&
        echo
